In [2]:
import math
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
X_train = X_train/255
X_test = X_test/255

In [6]:
X_train_flat = X_train.reshape(len(X_train),28*28)
X_test_flat = X_test.reshape(len(X_test),28*28)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train_flat,y_train,epochs=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8070 - loss: 0.7344
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9149 - loss: 0.3091
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9208 - loss: 0.2864
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9252 - loss: 0.2711
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9254 - loss: 0.2716


In [ ]:
model.evaluate(X_test_flat,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9145 - loss: 0.3049


[0.2687588632106781, 0.925599992275238]

In [ ]:
y_pred = model.predict(X_test_flat)
y_pred[1]

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


array([5.5358666e-01, 6.4127697e-03, 9.9932176e-01, 3.9223790e-01,
       6.0657412e-10, 8.9445990e-01, 9.2240328e-01, 8.1136730e-13,
       1.3491993e-01, 4.2564037e-09], dtype=float32)

In [ ]:
np.argmax(y_pred[1])

np.int64(2)

In [ ]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 963,    0,    0,    2,    0,    5,    7,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,   11,  916,   18,    7,    4,   13,   10,   39,    5],
       [   4,    0,   15,  912,    1,   35,    3,    9,   22,    9],
       [   1,    1,    3,    1,  913,    0,   13,    3,    9,   38],
       [  10,    2,    2,   23,    9,  791,   16,    5,   27,    7],
       [  12,    3,    4,    1,    7,   12,  916,    2,    1,    0],
       [   2,    7,   21,    7,    8,    1,    0,  943,    2,   37],
       [   6,   10,    7,   19,    9,   41,    9,    9,  857,    7],
       [  11,    7,    1,    9,   25,    7,    0,   14,    6,  929]],
      dtype=int32)>

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,),activation='relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train_flat,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8783 - loss: 0.4407
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9607 - loss: 0.1346
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9742 - loss: 0.0876
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9809 - loss: 0.0656
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9849 - loss: 0.0504


In [ ]:
model.evaluate(X_test_flat,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9696 - loss: 0.0996


[0.08575491607189178, 0.9747999906539917]

In [ ]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8739 - loss: 0.4500
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9611 - loss: 0.1328
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9722 - loss: 0.0934
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9793 - loss: 0.0669
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9846 - loss: 0.0498


In [8]:
df = pd.read_csv("insurance_data.csv")

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [10]:
X_train['age'] = X_train['age']/100
X_test['age'] = X_test['age']/100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7273 - loss: 0.5321
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7273 - loss: 0.5320
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7273 - loss: 0.5319
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7273 - loss: 0.5318
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.7273 - loss: 0.

In [ ]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - accuracy: 1.0000 - loss: 0.3550


[0.3549776077270508, 1.0]

In [ ]:
coef,intercept = model.get_weights()
coef,intercept

In [ ]:
def log_loss(y_true,y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon) for i in y_pred]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [ ]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [ ]:
def gradient_descent(age,affordibility,y_true, epochs,loss_threshold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = 28

    for i in range(epochs):
        wt_sum = w1*age + w2*affordibility +bias
        y_pred = sigmoid_numpy(wt_sum)

        loss = log_loss(y_true,y_pred)
        w1d = (1/n)*np.dot(np.transpose(age),(y_pred-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
        bias_d = np.mean(y_pred-y_true)

        w1 = w1 - rate*w1d
        w2 = w2 - rate*w2d
        bias = bias - rate*bias_d

        print(f'Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')

        if loss<=loss_threshold:
           break

    return w1, w2, bias


In [ ]:
gradient_descent(X_train['age'],X_train['affordibility'],y_train,1000,0.4631)

Epoch:0,w1:0.9802845691551391,w2:0.9594163842385585,bias:-0.11341867736368583,loss:0.7113403233723417
Epoch:1,w1:0.9648609942838093,w2:0.9254814701909777,bias:-0.2130507456932445,loss:0.6824220360876523
Epoch:2,w1:0.9533948144439239,w2:0.8977876063231004,bias:-0.30002642408510166,loss:0.6606256909896735
Epoch:3,w1:0.9454890771477951,w2:0.8757807141495089,bias:-0.37565260670920353,loss:0.6444401866735966
Epoch:4,w1:0.9407224446022916,w2:0.8588297172988666,bias:-0.4412944972009035,loss:0.632533113481166
Epoch:5,w1:0.9386788937076169,w2:0.8462843161045234,bias:-0.4982854999877191,loss:0.6238029679289645
Epoch:6,w1:0.9389676525336592,w2:0.8375163276361743,bias:-0.5478682951131203,loss:0.6173829725434178
Epoch:7,w1:0.9412344661950837,w2:0.8319452031929134,bias:-0.591162852078605,loss:0.6126161992640902
Epoch:8,w1:0.9451663014644478,w2:0.8290509331948583,bias:-0.6291544071389849,loss:0.6090186985738805
Epoch:9,w1:0.9504916527665189,w2:0.8283781025207518,bias:-0.6626945549058285,loss:0.606241

(np.float64(5.037078124234488),
 np.float64(1.4797569666049377),
 np.float64(-2.9764124066382003))

In [ ]:
class myNN:
  def __init__(self):
      self.w1 = 1
      self.w2 = 1
      self.bias = 0

  def fit(self,X,y,epochs,loss_threshold):
      self.w1,self.w2,self.bias = self.gradient_descent(X['age'],X['affordibility'],y,epochs,loss_threshold)

  def predict(self,X_test):
      weighted_sum = self.w1*X_test['age']+self.w2*X_test['affordibility']+self.bias
      return sigmoid_numpy(weighted_sum)

  def gradient_descent(self,age,affordibility,y_true, epochs,loss_threshold):
      w1 = w2 = 1
      bias = 0
      rate = 0.5
      n = 28

      for i in range(epochs):
          wt_sum = w1*age + w2*affordibility +bias
          y_pred = sigmoid_numpy(wt_sum)

          loss = log_loss(y_true,y_pred)
          w1d = (1/n)*np.dot(np.transpose(age),(y_pred-y_true))
          w2d = (1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
          bias_d = np.mean(y_pred-y_true)

          w1 = w1 - rate*w1d
          w2 = w2 - rate*w2d
          bias = bias - rate*bias_d

          if i%50==0:
             print(f'Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')

          if loss<=loss_threshold:
            break

      return w1, w2, bias


In [ ]:
customModel = myNN()
customModel.fit(X_train,y_train,epochs=500,loss_threshold=0.4631)

Epoch:0,w1:0.9802845691551391,w2:0.9594163842385585,bias:-0.11341867736368583,loss:0.7113403233723417
Epoch:50,w1:1.4094276762135143,w2:1.0963026246257566,bias:-1.1974494620716971,loss:0.5710644420300536
Epoch:100,w1:1.9890309136327278,w2:1.2855005657305691,bias:-1.5766662333741395,loss:0.5461120189481622
Epoch:150,w1:2.5358558826641695,w2:1.3724996908301819,bias:-1.8669931989525204,loss:0.5270332218146803
Epoch:200,w1:3.0454183917328344,w2:1.4145176590514457,bias:-2.108288584048192,loss:0.5113390123546256
Epoch:250,w1:3.517606441482049,w2:1.436764604390609,bias:-2.3192498934056505,loss:0.49814125560876543
Epoch:300,w1:3.9542308397259296,w2:1.4506532170742221,bias:-2.5092309617891204,loss:0.4869490023464534
Epoch:350,w1:4.357867716000735,w2:1.4613518989078023,bias:-2.6832319554673147,loss:0.4774103997805575
Epoch:400,w1:4.731294700282642,w2:1.4711388089376198,bias:-2.844149233136772,loss:0.4692477728163935


In [ ]:
customModel.predict(X_test)

2     0.704906
10    0.356639
21    0.158855
11    0.478445
14    0.725421
9     0.828632
dtype: float64